Repository openshift/troubleshooting-panel-console-plugin, pull requests merged in 2024-05, with the labels that each got.

#5 Add Troubleshooting Panel
  .gitignore
  Makefile
  README.md
  scripts/start-console.sh
  scripts/start-forward.sh
  troubelshooting-panel.yaml
  web/console-extensions.json
  web/i18n-scripts/build-i18n.sh
  web/i18n-scripts/common.js
  web/i18n-scripts/lexers.js
  web/i18n-scripts/set-english-defaults.js
  web/integration-tests/cypress.config.js
  web/integration-tests/support/index.ts
  web/integration-tests/support/login.ts
  web/integration-tests/tests/example-page.cy.ts
  web/integration-tests/tests/k8s-node.cy.ts
  web/jest.config.js
  web/locales/en/plugin__troubleshooting-panel-console-plugin.json
  web/package-lock.json
  web/package.json
  web/src/URLSearchParams.d.ts
  web/src/__tests__/alert-node.spec.ts
  web/src/__tests__/korrel8r-url-parsing.spec.ts
  web/src/__tests__/log-node.spec.ts
  web/src/__tests__/metric-node.spec.ts
  web/src/__tests__/netflow-node.spec.ts
  web/src/cancellable-fetch.ts
  web/src/components/Korrel8rPage.tsx
  web/src/components/Korrel8rPanel.tsx
  web/src/components/Korrel8rTopology.tsx
  web/src/components/LoadingTopology.tsx
  web/src/components/Popover.tsx
  web/src/components/example.css
  web/src/components/korrel8rpanel.css
  web/src/components/popover.css
  web/src/getResources.ts
  web/src/hooks/useBoolean.ts
  web/src/hooks/useKorrel8r.ts
  web/src/hooks/usePluginAvailable.ts
  web/src/hooks/useQueryParams.ts
  web/src/hooks/useTroubleshootingPanel.tsx
  web/src/hooks/useURLState.ts
  web/src/korrel8r-client.ts
  web/src/korrel8r-utils.ts
  web/src/korrel8r/alert.ts
  web/src/korrel8r/k8s.ts
  web/src/korrel8r/korrel8r.types.ts
  web/src/korrel8r/log.ts
  web/src/korrel8r/metric.ts
  web/src/korrel8r/netflow.ts
  web/src/korrel8r/node-factory.ts
  web/src/korrel8r/query.types.ts
  web/src/redux-actions.ts
  web/src/redux-reducers.ts
  web/tsconfig.json
  web/webpack.config.ts
Labels: lgtm

#9 OU-378: Add a Go Backend
  .dockerignore
  Dockerfile
  Makefile
  README.md
  charts/openshift-console-plugin/templates/_helpers.tpl
  charts/openshift-console-plugin/templates/configmap.yaml
  charts/openshift-console-plugin/templates/consoleplugin.yaml
  charts/openshift-console-plugin/templates/deployment.yaml
  charts/openshift-console-plugin/templates/patch-consoles-job.yaml
  charts/openshift-console-plugin/templates/patcher-clusterrole.yaml
  charts/openshift-console-plugin/templates/patcher-clusterrolebinding.yaml
  charts/openshift-console-plugin/templates/service.yaml
  charts/openshift-console-plugin/values.yaml
  cmd/plugin-backend.go
  go.mod
  go.sum
  pkg/manifest_handler.go
  pkg/server.go
  pkg/server_test.go
  pkg/testdata/index.html
  pkg/testdata/plugin-entry.js
  scripts/build-image.sh
  scripts/start-forward.sh
  troubelshooting-panel.yaml
  web/package.json
Labels: jira/valid-reference, approved

#10 Update documentation to avoid pitfalls when installing
  README.md
Labels: lgtm, approved

#12 fix makefile command
  Dockerfile
  Makefile
  web/package-lock.json
  web/package.json
Labels: lgtm, approved
