Repository openshift/troubleshooting-panel-console-plugin, pull requests merged in 2024-11, with the labels that each got.

#91 NO-JIRA: Fix an issue calling private methods in a static function
  web/src/korrel8r/k8s.ts
Labels: lgtm, jira/valid-reference, approved

#92 NO-JIRA: Fix an issue which never returned a node
  web/src/korrel8r/node-factory.ts
Labels: lgtm, jira/valid-reference, approved

#95 test: Add more unit tests, run tests from Makefile.
  Makefile
  web/jest.config.js
  web/src/__tests__/k8s-node.spec.ts
  web/src/__tests__/metric-node.spec.ts
  web/src/__tests__/node-factory.spec.ts
  web/src/__tests__/trace-node.spec.ts
  web/src/korrel8r/metric.ts
  web/tsconfig.json
Labels: lgtm, approved

#96 fix: trace fixes for troubleshooting panel
  Makefile
  web/src/__tests__/node-factory.spec.ts
  web/src/__tests__/trace-node.spec.ts
  web/src/korrel8r/trace.ts
  web/tsconfig.json
Labels: lgtm, approved

#97 fix(COO-544): Troubleshooting panel shows "invalid query".
  Makefile
  web/locales/en/plugin__troubleshooting-panel-console-plugin.json
  web/src/components/Korrel8rPanel.tsx
  web/src/components/topology/Korrel8rTopology.tsx
  web/src/korrel8r-utils.ts
  web/src/korrel8r/invalid.ts
Labels: lgtm, ok-to-test, approved

#104 fix(COO-550): Net flow Console URL to korrel8r query translation issues.
  web/src/components/Korrel8rPanel.tsx
  web/src/korrel8r/netflow.ts
Labels: lgtm, approved

#102 Manual cherry pick for #96
  Makefile
  web/src/__tests__/node-factory.spec.ts
  web/src/__tests__/trace-node.spec.ts
  web/src/korrel8r/trace.ts
  web/tsconfig.json
Labels: lgtm, approved

#106 fix(COO-557): Remove spurious '|json' in log queries.
  web/src/__tests__/log-node.spec.ts
  web/src/__tests__/node-factory.spec.ts
  web/src/korrel8r/log.ts
Labels: lgtm, approved

#111 fix(minor): Typo in error message, not using string expansion.
  web/src/korrel8r/metric.ts
Labels: lgtm, approved

#112 Update readme with correct commands
  README.md
Labels: lgtm, approved
